services:
  telurio-api:
    image: ghcr.io/yohanestedy/telurio-api:latest

    restart: unless-stopped

    env_file:
      - .env

    expose:
      - "3000"

    networks:
      - global-network

    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  global-network:
    external: true